apiVersion: v1
kind: Pod
metadata:
  name: nfs-demo-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: webdata
          mountPath: /usr/share/nginx/html
  volumes:
    - name: webdata
      persistentVolumeClaim:
        claimName: test-dynamic-volume-claim

